### ISSUE TITLE
No sync working

### ISSUE THREAD

**Issue by alangrafu** [silverbulletmd/silverbullet-git#3]
I installed a fresh silverbullet instance. My PLUGS page looks like this

```yaml
- github:silverbulletmd/silverbullet-git/git.plug.js
- github:silverbulletmd/silverbullet-backlinks/backlinks.plug.js
```

When I run "sync" the logs show there is an error. Not sure if this is because the installation is wrong or something in the pluging?

```
silverbullet    | Loading file PLUGS.md
silverbullet    | Error NotFound: No such file or directory (os error 2)
silverbullet    |     at spawnChildInner (ext:runtime/40_process.js:162:17)
silverbullet    |     at spawn (ext:runtime/40_process.js:347:10)
silverbullet    |     at Command.output (ext:runtime/40_process.js:420:12)
silverbullet    |     at file:///silverbullet.js:60799:38
silverbullet    |     at eventLoopTick (ext:core/01_core.js:181:11)
silverbullet    |     at async dispatch (file:///silverbullet.js:59442:7)
silverbullet    |     at async dispatch (file:///silverbullet.js:59442:7)
silverbullet    |     at async dispatch (file:///silverbullet.js:59442:7)
silverbullet    |     at async dispatch (file:///silverbullet.js:59442:7)
silverbullet    |     at async file:///silverbullet.js:60675:9 {
silverbullet    |   name: "NotFound",
silverbullet    |   code: "ENOENT"
silverbullet    | }
```

**Comment by zefhemel** [comment]
Hmm, odd. Do you have git installed on the machine where you're running this? It uses the regular `git` binary.

**Comment by alangrafu** [comment]
I'm using the official docker image, which doesn't seem to bring git with it. I can close this issue then, but it would be great to add a comment in the documentation, thanks!
